### ISSUE TITLE
Twig inspector is depending on "oro_platform.twig.service_locator"

### ISSUE THREAD

**Issue by pauliuslukosiunas** [oroinc/twig-inspector#3]
I think that it should be not depended from it :) or at lease added that to it self.

**Comment by anyt** [comment]
Hi Paulius,

Thank you for your interest in the twig inspector.

We know about this issue and it will be fixed in a next patch release.
Please use a stable version of an extension. The latest available version is  `1.0.1`. It doesn't have this dependency, so there should be no issues.
