### ISSUE TITLE
Fallback or message when no ide is configured

### ISSUE THREAD

**Issue by Guite** [oroinc/twig-inspector#5]
Hello,

we are currently considering including twig-inspector into the [Zikula core](https://github.com/zikula/core/).
https://github.com/zikula/core/pull/4100
So far we are very pleased about this component. Thanks for your great work!

One little thing we noticed:
If no IDE or editor is configured Symfony uses the browser as a fallback when clicking on a source file in the Symfony profiler. For the twig-inspector there is no such fallback yet.

It would be great if:

* either (preferably) twig-inspector could do the same as Symfony does so even without a configured editor things work (prevent a 404 page)
* or (alternatively) a message could be shown (for example [here](https://raw.githubusercontent.com/oroinc/twig-inspector/master/Bundle/Resources/doc/images/toolbar-extension-icon.png)) so the user knows that he needs to configure something in `/config/packages/dev/framework.yaml`. I have added documentation, but this is not directly visible and it would avoid a frustrating experience if twig-inspector could directly inform the user that something is missing.
* a third solution (which could be combined with a message) could be that if no editor is configured file paths are just shown but not linked.

**Comment by anyt** [comment]
Hi @Guite ,

I've just tested it in a clean Symfony 5 installation, without defining `framework.ide` option. And it fallbacks to the web browser.
![Screenshot with opened template](https://i.imgur.com/QxiQ52K.png)

Please follow [the installation guide](https://github.com/oroinc/twig-inspector/blob/master/Bundle/Resources/doc/installation.md) to make sure you configured the extension correctly.

**Comment by Guite** [comment]
Hi @anyt,

I can only see one difference: in your example the file path is relative.

Here is an example from my installation:

![Screenshot_20200203_223732](https://user-images.githubusercontent.com/277531/73693039-c8db1200-46d5-11ea-8fd7-d41435544727.png)

Leads to:

![Screenshot_20200203_223805](https://user-images.githubusercontent.com/277531/73693083-ddb7a580-46d5-11ea-9508-c265bf4cd0bc.png)

Does this maybe help you to reproduce the problem?

**Comment by anyt** [comment]
Maybe you can share the branch in your repository, where I can reproduce the bug?

**Comment by Guite** [comment]
It is the master branch: https://github.com/zikula/core/tree/master

**Comment by Guite** [comment]
I think I found the problem: it only occurs if your system is in a sub directory.
So if you are using e.g. `http://localhost/public/` (or any other directory) it still tries to open `http://localhost/_profiler/open?file=...` instead of `http://localhost/public/_profiler/open?file=...`

Also there seems a problem with parameter encoding: it redirects to `&amp;line=365#line365` instead of `&line=365#line365`.

Will investigate further and try to add a PR for that.

**Comment by Guite** [comment]
Fixed in version 1.0.3.
