### ISSUE TITLE
Symfony 6 Compatibilty

### ISSUE THREAD

**Issue by natewiebe13** [oroinc/twig-inspector#7]
Currently this bundle is not compatible with Symfony 6. I also noticed that compatibility goes back quite far, and could make it more difficult to maintain. Thoughts on removing some older versions for Symfony and Twig from support?

**Comment by anyt** [comment]
Hi Nate,
We have to support Symfony 5.4 LTS, and all the twig versions, lower versions support can be dropped.
Feel free to contribute.

**Comment by natewiebe13** [comment]
Luckily there wasn't anything that really changed with parts of Symfony this touches, so no support has been dropped! I did add a php restriction, dropping EOL versions of PHP and to ensure we can use some of the newer language features. But it looks like there was already code that shouldn't function < 7.4 anyways.

**Comment by natewiebe13** [comment]
Hey @anyt any chance we can get this reviewed and tagged soon?

**Comment by anyt** [comment]
Hi, I'm going to review it by the end of the week. Sorry, it takes so long.

**Comment by anyt** [comment]
Released 1.1.0. 

Thank you for your contribution, @natewiebe13!
